CREATE TABLE dbo.Tabela1(NUMERO_TAB1 NUMERIC(6,0) NOT NULL)
CREATE TABLE dbo.Tabela2(NUMERO_TAB2 NUMERIC(6,0) NOT NULL)

INSERT INTO dbo.Tabela1(NUMERO_TAB1) VALUES (100);
INSERT INTO dbo.Tabela2(NUMERO_TAB2) VALUES (200);

SELECT * FROM dbo.Tabela1;
SELECT * FROM dbo.Tabela2;

SELECT SUM(X.TOTAL) AS Total
	FROM(
		SELECT SUM(NUMERO_TAB1) as Total FROM dbo.Tabela1
		UNION ALL
		SELECT SUM(NUMERO_TAB2) as Total FROM dbo.Tabela2
		) X;
